<Project Sdk="Godot.NET.Sdk/4.6.2">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <Nullable>enable</Nullable>
    <ImplicitUsings>true</ImplicitUsings>
    <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\SharpIDE.FSharp\SharpIDE.FSharp.fsproj" />
    <ProjectReference Include="..\..\tools\GodotServiceDefaults\GodotServiceDefaults.csproj" PrivateAssets="all" />
    <ProjectReference Include="..\SharpIDE.Application\SharpIDE.Application.csproj" />
     <!-- For build order -->
    <ProjectReference Include="..\SharpIDE.MsBuildHost\SharpIDE.MsBuildHost.csproj" ReferenceOutputAssembly="false" Private="false" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Http" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" />
    <PackageReference Include="ObservableCollections" />
    <PackageReference Include="ObservableCollections.R3" />
    <PackageReference Include="Octokit" />
    <PackageReference Include="R3" />
    <PackageReference Include="Krafs.Publicizer">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
      <Publicize Include="Microsoft.CodeAnalysis.Workspaces" />
      <Publicize Include="Microsoft.CodeAnalysis.Features" />
      <Publicize IncludeCompilerGeneratedMembers="false" Include="GodotSharp" MemberPattern="^(?:Godot\.StringName\.NativeValue|Godot\.CodeEdit\.MethodBind31|Godot\.GodotObject\.GetPtr)" />
      <DoNotPublicize Include="Microsoft.CodeAnalysis.Workspaces:System.Linq.RoslynEnumerableExtensions" />
  </ItemGroup>

  <ItemGroup>
    <None Include="version.txt" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Properties\launchSettings.json" />
    <Content Include="..\update-sharpide.cs" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>

    <Target Name="CopyBuildHostOutputToOutput" AfterTargets="Build">
        <PropertyGroup>
            <!-- Godot publishes for a specific RID, e.g. '-r win-x64' which affects the output folder of the BuildHost project. -->
            <BuildHostFilesFolderName Condition="'$(RuntimeIdentifier)' != ''">$(Configuration)_$(RuntimeIdentifier)</BuildHostFilesFolderName>
            <BuildHostFilesFolderName Condition="'$(RuntimeIdentifier)' == ''">$(Configuration)</BuildHostFilesFolderName>
            <BuildHostFilesFolderName>$([System.String]::Copy('$(BuildHostFilesFolderName)').ToLowerInvariant())</BuildHostFilesFolderName>
        </PropertyGroup>
        <ItemGroup>
            <BuildHostFiles Include="$(ArtifactsPath)\bin\SharpIDE.MsBuildHost\$(BuildHostFilesFolderName)\**\*.*" />
        </ItemGroup>

        <MakeDir Directories="$(OutputPath)SharpIdeMsBuildHost" />

        <Copy SourceFiles="@(BuildHostFiles)"
              DestinationFiles="@(BuildHostFiles->'$(OutputPath)SharpIdeMsBuildHost\%(RecursiveDir)%(Filename)%(Extension)')"
              SkipUnchangedFiles="true" />
    </Target>

    <Target Name="CleanBuildHostOutput" AfterTargets="Clean">
        <RemoveDir Directories="$(OutputPath)SharpIdeMsBuildHost" />
    </Target>

    <Target Name="CopyBuildToPublish" AfterTargets="Publish">
        <ItemGroup>
            <BuildHostFiles Include="$(OutputPath)SharpIdeMsBuildHost\**\*.*" />
        </ItemGroup>
        <MakeDir Directories="$(PublishDir)SharpIdeMsBuildHost" />
        <Copy SourceFiles="@(BuildHostFiles)"
              DestinationFiles="@(BuildHostFiles->'$(PublishDir)SharpIdeMsBuildHost\%(RecursiveDir)%(Filename)%(Extension)')"
              SkipUnchangedFiles="true" />
    </Target>
</Project>